services:
  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: "code-test"
      POSTGRES_USER: "pg-user"
      POSTGRES_PASSWORD: "pg-password"
    networks:
      - app_network
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    platform: linux/x86_64/v8
    image: ghcr.io/metalabdesign/ml-eng-assignment-backend:latest
    env_file:
      - ./.env
    environment:
      STATIC_API_KEY: ${API_KEY}
      COREPACK_ENABLE_STRICT: "0"
    command: [sh, -c, "cd apps/api && pnpm start:migrate"]
    networks:
      - app_network
    ports:
      - "3001:3001"
    depends_on:
      - postgres

networks:
  app_network:
    external: true

volumes:
  postgres:
